### ISSUE TITLE
Diagnostic Window Hangs

### ISSUE THREAD

**Issue by pgkt04** [KN4CK3R/ReClass.NET-MemoryPipePlugin#1]
Can I get some help with this?
Loading the plugin is fine and all, but after I inject and I attempt to attach - I get a non responsive diagnostic window and fails to attach.

Also the one time the window did load, it said “illegal characters in path (mscorlib)”

I’m not sure at all how to debug this, some help would be greatly appreciated!

**Comment by KN4CK3R** [comment]
Do you get this error with every target process or could an anti cheat tool block the connection?

**Comment by pgkt04** [comment]
> Do you get this error with every target process or could an anti cheat tool block the connection?

every single process

**Comment by pgkt04** [comment]
```
     client.Send(new ReadMemoryRequest(address, size));
```

I believe its crashing in the ReadRemoteMemory function
Crash message: Arithmetic operation resulted in an overflow. (MemoryPipePlugin)

**Comment by pgkt04** [comment]
did some more debugging

turns out inside the ReadMemoryRequest WriteTo function is crashing

**Comment by pgkt04** [comment]
Fixed this! Simply do #define WIN64 at the top of Extensions.cs for anyone else wondering - (note this is for 64 bit programs), note to KN4CK3R add DefineConstants for the win64 builds

**Comment by KN4CK3R** [comment]
It's fixed now, thank you for the report.
